### ISSUE TITLE
what if we encounter collisions?

### ISSUE THREAD

**Issue by ng-model** [dbanksdesign/style-dictionary-example-component-scss#1]
Hello @dbanksdesign I am a big fan of your work and new to style-dictionary. During the process of generating the tokens to respective scss file, How can we easily solve collisions.. Below posted is just an example of one of the collisions i faced.

```
Property Value Collisions:
Collision detected at: font-weight.w1! Original value: UltLt, New value: Ultra Light
Collision detected at: font-weight.w1! Original value: 250, New value: 250
Collision detected at: font-weight.w2! Original value: Light, New value: Regular
Collision detected at: font-weight.w2! Original value: 300, New value: 400
Collision detected at: font-weight.w3! Original value: Regular, New value: Medium
```

**Comment by dbanksdesign** [comment]
Collisions happen when you have multiple source files that define the same thing. For example, say you have 2 source JSON files:

```json
{
  "color": {
    "base": {
      "gray": {
        "light" : { "value": "#CCCCCC" },
        "medium": { "value": "#999999" },
        "dark"  : { "value": "#111111" }
      },
      "red": { "value": "#FF0000" },
      "green": { "value": "#00FF00" }
    }
  }
}
```

And

```json
{
  "color": {
    "base": {
      "gray": {
        "light" : { "value": "#EEEEEE" },
      }
    }
  }
}
```

You would get a collision at `color.base.gray.light` because 2 different files defined that same token. This could be intended, which is why Style Dictionary shows it as a warning rather than throwing an error. Sometimes this isn't want is intended because only one of those values will take effect. 

If you do want to use a base set of tokens and override certain ones, for example creating multiple brands or themes, you can use the `include` parameter in the configuration to include the base set of tokens. Style Dictionary will not show a warning if there is a collision between `include` files and `source` files because that is what `include` is intended for. 

If you post the code of your project that led you to get these warnings I can help debug specifically what is happening. Hope this helps!

**Comment by ng-model** [comment]
I was doing the same but still see collisions. Thanks.

**Comment by ng-model** [comment]
https://github.com/amzn/style-dictionary/issues/411
